import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const root = resolve(dirname(__filename), '..')
const envPath = resolve(root, '.env')
const envLocalPath = resolve(root, '.env.local')

if (!existsSync(envPath)) {
  console.error('No .env found. Run `stripe projects env --pull --yes` first.')
  process.exit(1)
}

function parseEnv(text) {
  const out = {}
  const lines = text.split(/\r?\n/)
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    let value = trimmed.slice(eq + 1).trim()
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1)
    }
    out[key] = value
  }
  return out
}

const env = parseEnv(readFileSync(envPath, 'utf8'))

const clerkRaw =
  env.CLERK_AUTH_ENVIRONMENTS ?? env.CLERK_ENVIRONMENTS ?? null
if (!clerkRaw) {
  console.error(
    'Missing CLERK_(AUTH_)ENVIRONMENTS. Did you run `stripe projects add clerk/auth`?',
  )
  process.exit(1)
}

let clerkParsed
try {
  clerkParsed = JSON.parse(clerkRaw)
} catch (err) {
  console.error('Could not parse Clerk envs JSON:', err.message)
  process.exit(1)
}

const dev = clerkParsed.development ?? clerkParsed.production
if (!dev?.publishable_key || !dev?.secret_key) {
  console.error('Clerk environments missing publishable_key or secret_key.')
  process.exit(1)
}

const connection =
  env.NEON_POSTGRES_CONNECTION_STRING ?? env.DATABASE_URL ?? null
if (!connection) {
  console.error(
    'Missing NEON_POSTGRES_CONNECTION_STRING. Did you run `stripe projects add neon/postgres`?',
  )
  process.exit(1)
}

const posthogKey = env.POSTHOG_ANALYTICS_API_KEY ?? env.POSTHOG_API_KEY ?? ''
const posthogHost =
  env.POSTHOG_ANALYTICS_HOST ?? env.POSTHOG_HOST ?? 'https://us.i.posthog.com'

const sentryDsn = env.SENTRY_DSN ?? ''
const sentryOrg = env.SENTRY_ORG ?? ''
const sentryProject = env.SENTRY_PROJECT ?? ''
const sentryAuthToken = env.SENTRY_AUTH_TOKEN ?? ''

const out = [
  '# Auto-generated by scripts/setup-env.mjs from values in .env',
  '# Re-run `npm run setup:env` after `stripe projects env --pull --yes`.',
  '',
  '# Clerk',
  `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${dev.publishable_key}`,
  `CLERK_SECRET_KEY=${dev.secret_key}`,
  `NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in`,
  `NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up`,
  `NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL=/dashboard`,
  `NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL=/dashboard`,
  '',
  '# Database',
  `DATABASE_URL=${connection}`,
  '',
  '# PostHog',
  `NEXT_PUBLIC_POSTHOG_KEY=${posthogKey}`,
  `NEXT_PUBLIC_POSTHOG_HOST=${posthogHost}`,
  '',
  '# Sentry',
  `NEXT_PUBLIC_SENTRY_DSN=${sentryDsn}`,
  `SENTRY_DSN=${sentryDsn}`,
  `SENTRY_ORG=${sentryOrg}`,
  `SENTRY_PROJECT=${sentryProject}`,
  `SENTRY_AUTH_TOKEN=${sentryAuthToken}`,
  '',
].join('\n')

writeFileSync(envLocalPath, out)
console.log('Wrote .env.local with derived values.')
